-- RLS有効化 + anon/authenticatedロールのアクセス剥奪
-- Supabase脆弱性対策: REST API経由の不正アクセスを防止

-- 全テーブルでRLS有効化（ポリシーなし = 全拒否）
ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_token" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_setting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_action" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "content" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "content_tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "feed_source" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "delivery_batch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "delivery_batch_item" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "weekly_ranking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "code_master" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "domain_banlist" ENABLE ROW LEVEL SECURITY;

-- anon/authenticatedロールからpublicスキーマの全テーブルへのアクセスを剥奪
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM authenticated;
  END IF;
END $$;

-- デフォルト権限も剥奪（今後新規作成されるテーブルにも適用）
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM authenticated;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM authenticated;
  END IF;
END $$;
